"""APDL export: the "reference full model" -- a full-resolution FEM mesh
built directly from a layer's sub-pixel copper raster, one element per
raster cell, material-assigned Cu vs PPG (prepreg).

This mirrors exactly what the left display panel shows
(TraceGridMapper._raster_bitmap) -- as opposed to the coarse nx x ny
equivalent-property grid the rest of the pipeline produces. It exists to
serve as a ground-truth model to validate the coarse equivalent-property
model against, hence "reference full model".

A real board can rasterise to millions of cells, so node/element/material
data is built with vectorised numpy operations (boolean masking + one bulk
`np.savetxt` write per material group) -- there is no per-element Python
loop.
"""

import numpy as np
from pathlib import Path

# ---------------------------------------------------------------------------
#  Placeholder material properties -- TEMPORARY.
#  Replace with real Cu / PPG (prepreg) data before running a real analysis.
#  Assumed consistent unit system: length=mm, force=N, stress/modulus=MPa,
#  density=ton/mm^3, thermal conductivity=W/(mm*K) (note mm, not m --
#  datasheet W/(m*K) values need dividing by 1000 to fit this unit system).
# ---------------------------------------------------------------------------
CU_PROPS = {
    'EX': 110000.0,     # Young's modulus, MPa
    'PRXY': 0.34,       # Poisson's ratio
    'DENS': 8.96e-9,    # density, ton/mm^3
    'ALPX': 17.0e-6,    # CTE, 1/K
    'KXX': 0.385,       # thermal conductivity, W/(mm*K)
}
PPG_PROPS = {
    'EX': 20000.0,
    'PRXY': 0.12,
    'DENS': 1.90e-9,
    'ALPX': 15.0e-6,
    'KXX': 0.0003,
}


def write_reference_full_model_apdl(mapper, filepath,
                                    cu_props=None, ppg_props=None,
                                    elem_type='PLANE182', thickness=0.035,
                                    stride=1, title='REFERENCE FULL MODEL'):
    """Write an APDL macro building the mesh exactly as shown in the raster
    display: one 2D element per raster sub-pixel, MAT=1 (Cu) or MAT=2 (PPG)
    depending on that pixel's copper/empty state.

    Args:
        mapper: a TraceGridMapper. `.compute()` is called here if the
                raster bitmap isn't already available.
        filepath: output .mac path.
        cu_props / ppg_props: dict of APDL MP labels -> values, overriding
                the CU_PROPS / PPG_PROPS placeholders above.
        elem_type: 2D element type. PLANE182 (structural, default) or
                PLANE55 (thermal) both work -- MP labels irrelevant to the
                chosen element/analysis type are simply unused, not errors.
        thickness: shared layer thickness (mm), written as real constant 1
                (used when elem_type honors KEYOPT(3)=3, plane stress with
                thickness).
        stride: use every `stride`-th raster cell per axis instead of all
                of them, to bound element count for very large boards.
                1 (default) matches the display panel exactly.
        title: header comment / model title.

    Returns:
        dict with node_count, element_count, cu_element_count.
    """
    if mapper._raster_bitmap is None:
        mapper.compute()

    bitmap = mapper._raster_bitmap
    if stride > 1:
        bitmap = bitmap[::stride, ::stride]
    ny_s, nx_s = bitmap.shape

    xmin, ymin, xmax, ymax = mapper.bounds
    x_edges = np.linspace(xmin, xmax, nx_s + 1)
    y_edges = np.linspace(ymin, ymax, ny_s + 1)
    XX, YY = np.meshgrid(x_edges, y_edges)

    node_ids = (np.arange((nx_s + 1) * (ny_s + 1), dtype=np.int64)
               .reshape(ny_s + 1, nx_s + 1) + 1)

    # Element corner nodes, vectorised over the whole (ny_s, nx_s) cell
    # grid at once -- CCW winding (n1 bottom-left -> n4 top-left).
    n1 = node_ids[:-1, :-1]
    n2 = node_ids[:-1, 1:]
    n3 = node_ids[1:, 1:]
    n4 = node_ids[1:, :-1]

    is_cu = bitmap

    cu = {**CU_PROPS, **(cu_props or {})}
    ppg = {**PPG_PROPS, **(ppg_props or {})}

    n_nodes = int(node_ids.size)
    n_elems = int(nx_s) * int(ny_s)
    n_cu = int(is_cu.sum())

    main_path = Path(filepath)
    stem = main_path.stem
    node_name, elem_name = f"{stem}_node", f"{stem}_elem"
    node_path = main_path.with_name(f"{node_name}.mac")
    elem_path = main_path.with_name(f"{elem_name}.mac")

    # Bulk N,/E, data lives in its own macro so the main file stays readable
    # and an editor can open it. /NOPR around each /INPUT suppresses the
    # per-command echo, which is what makes reading millions of lines slow.
    with open(node_path, 'w') as f:
        f.write(f"! Nodes for {stem} -- {n_nodes} nodes, generated by "
                "trace_mapping.apdl_export\n")
        f.write(f"! Included from {main_path.name}; do not run standalone.\n")
        node_table = np.column_stack([
            node_ids.ravel().astype(np.float64), XX.ravel(), YY.ravel(),
            np.zeros(n_nodes),
        ])
        np.savetxt(f, node_table, fmt=['N,%d', '%.6f', '%.6f', '%.6f'], delimiter=',')

    with open(elem_path, 'w') as f:
        f.write(f"! Elements for {stem} -- {n_elems} elements "
                f"({n_cu} Cu / {n_elems - n_cu} PPG), generated by "
                "trace_mapping.apdl_export\n")
        f.write(f"! Included from {main_path.name}; do not run standalone "
                "-- ET/MP/R/TYPE/REAL are set there.\n")
        for mat_id, mask, label in ((1, is_cu, 'Cu'), (2, ~is_cu, 'PPG')):
            count = int(mask.sum())
            f.write(f"MAT,{mat_id}   ! {label}: {count} elements\n")
            if count:
                elems = np.column_stack([n1[mask], n2[mask], n3[mask], n4[mask]]).astype(np.float64)
                np.savetxt(f, elems, fmt=['E,%d', '%d', '%d', '%d'], delimiter=',')

    with open(main_path, 'w') as f:
        f.write(f"! {title}\n")
        f.write("! Auto-generated by trace_mapping.apdl_export -- reference full model\n")
        f.write(f"! One element per raster sub-pixel ({nx_s} x {ny_s} = {n_elems} elements),\n")
        f.write(f"! matching the display panel exactly (stride={stride}).\n")
        f.write("! Placeholder Cu/PPG material properties -- replace before real analysis.\n")
        f.write("! Assumed consistent unit system: mm-ton-s-N-MPa; KXX in W/(mm*K).\n")
        f.write(f"! Node and element data are in {node_path.name} and "
                f"{elem_path.name};\n")
        f.write("! keep all three together and run ANSYS from their directory,\n")
        f.write("! since /INPUT below resolves them against the working directory.\n")
        f.write("/PREP7\n")
        f.write(f"ET,1,{elem_type}\n")
        f.write("KEYOPT,1,3,3   ! plane stress w/ real-constant thickness (ignored if elem_type doesn't use it)\n")
        f.write(f"R,1,{thickness}\n")
        for label, value in cu.items():
            f.write(f"MP,{label},1,{value}\n")
        for label, value in ppg.items():
            f.write(f"MP,{label},2,{value}\n")
        f.write("REAL,1\n")
        f.write("TYPE,1\n")

        f.write(f"! --- Nodes ({n_nodes}) ---\n")
        f.write("/NOPR\n")
        f.write(f"/INPUT,{node_name},mac\n")
        f.write("/GOPR\n")

        f.write(f"! --- Elements ({n_elems} total, {n_cu} Cu / {n_elems - n_cu} PPG) ---\n")
        f.write("/NOPR\n")
        f.write(f"/INPUT,{elem_name},mac\n")
        f.write("/GOPR\n")

        f.write("ALLSEL,ALL\n")

    print(f"  APDL reference-full-model written: {main_path}")
    print(f"    + {node_path.name} ({n_nodes} nodes), "
          f"{elem_path.name} ({n_elems} elements)")
    print(f"    nodes={n_nodes}  elements={n_elems}  "
          f"Cu={n_cu} ({100*n_cu/n_elems:.1f}%)  PPG={n_elems - n_cu}")

    return {'node_count': n_nodes, 'element_count': n_elems,
            'cu_element_count': n_cu,
            'node_file': str(node_path), 'elem_file': str(elem_path)}
